var myString;
var myNum;
var myBool;
var myVar;
// let strArr: string[];
var strArr;
// let numArr: number[];
var numArr;
// let boolArr: boolean[];
var boolArr;
var strNumTuple;
myString = 'Hello World';
myNum = 5 + 5;
myBool = true;
myVar = 5;
strArr = ['Hello', 'World'];
numArr = [1, 2, 4];
boolArr = [true, false, true];
strNumTuple = ['Hello', 3];
var myVoid = null;
var myNull = null;
var myUndefined = undefined;
console.log(myString);
console.log(myNum);
console.log(myBool);
console.log(myVar);
console.log(strArr);
console.log(numArr);
console.log(boolArr);
console.log(strNumTuple);
console.log(myVoid);
console.log(myNull);
console.log(myUndefined);
